### ISSUE TITLE
Ensure all code and content in the CFSJ repo is moved to mega-map repo. 

### ISSUE THREAD

**Issue by charliehoffs** [dcl-covid-19/mega-map#52]
_Motivation:_ We are no longer using the CFSJ repo, and it contains valuable resources of use to the rest of our BAC team, and would be most easily searchable if in the BAC mega-map repo! 

_Description:_
Please move all code and content from https://github.com/codeforsanjose/bac-resources to this mega-map repo, so it is accessible to all volunteers working on BAC.

**Comment by mudkins** [comment]
I can try to do this!

**Comment by charliehoffs** [comment]
Anthony moved all CFSJ code to a branch in this mega-map repo called CFSJ-repo-move!
